### ISSUE TITLE
Domains

### ISSUE THREAD

**Issue by Milkhan** [romegasoftware/Multitenancy#34]
Thank you for this gorgeous package. 
How can we add different domains instead of subdomains?

Thank you

**Comment by Naoray** [comment]
You can't. This package does not offer support for different domain per tenant

**Comment by vahidalvandi** [comment]
please add this !

**Comment by Naoray** [comment]
If you want to create a PR feel free.

Otherwise you can also just pay for a solution https://servr.app/ 😬

**Comment by vahidalvandi** [comment]
how it work ?
