### ISSUE TITLE
Event on Tenant Match

### ISSUE THREAD

**Issue by Sourcefli** [romegasoftware/Multitenancy#37]
Thank you for the package!

I'm currently using this package in conjunction with Nova and the Nova Multitenancy package that youve created.

Currently, I dont see that there's any way to handle tasks when a tenant is established within the app (e.g. changing configs based on current tenant). 
Maybe an event thats fired when the tenant is saved within the ioc container?

Maybe I'm overlooking it? 

If not, before I implement my own system for it, is there any plan to add this for the package? If so, anytime soon? 
I'd prefer to utilize the package logic where possible.

Thanks again for these packages, really helping so far 👍

**Comment by Naoray** [comment]
So you want to receive an event everytime a user accesses an allowed tenant domain?

Currently we don't fire any event for this. I'd like to understand your use case a little better. What configs do you want to set?

A workaround would be to observe the `retrieved` event on the `Tenant` model, and check manually if the user is allowed to access this model before setting your configs

**Comment by bradenkeith** [comment]
This issue is outside the scope of the intended use of the package so I am closing this issue.
