### ISSUE TITLE
have simple question

### ISSUE THREAD

**Issue by vahidalvandi** [romegasoftware/Multitenancy#38]
hi . 
do this package support a user with multi tenancy ? 
1- user register and login the profile are the create multi tenant with multi subdomain . 
2- click to each subdomain then open it without login because subdomain itself???

please help me

**Comment by Naoray** [comment]
If you are asking if a `User` can have many `Tenants` = many subdomains - yes, that's possible with this package!

**Comment by vahidalvandi** [comment]
do this support his senario ?

login to example.com >> the show two tenants like bello 

foo.example.com
bar.example.com

then after click to foo.example.com login automatically??

**Comment by vahidalvandi** [comment]
i login in 

```
Route::get('/dashboard', function () {
    dd('logged in vahid');
})->middleware('auth');
```
do i can login this ?? without authentication ?

```
Route::get('/home', function () {
    dd(products::all());
})->middleware('auth','tenant.auth');
```

i tested it but need agin login in 
foo.example.com 
i want loggin foo.example.com  because this user logged it example.com

**Comment by Naoray** [comment]
Yes, you are right. I am not 100% sure, but I guess this is caused by how the sessions are stored within Laravel for each domain.

**Comment by vahidalvandi** [comment]
another solution !
if we change subdomain to path solve probleam

tenant1.example.com/product
change to 
example.com/tenant1/product

how i do it ?
