### ISSUE TITLE
Leaking tenant session data

### ISSUE THREAD

**Issue by bilogic** [romegasoftware/Multitenancy#47]
I think there is a possible session data leakage as session storage is not separated by tenants
See https://www.youtube.com/watch?v=cjWEZ5SKvIY

**Comment by madurapa** [comment]
You are safe if you utilize the route middlewares provided by the package.

`'tenant.auth' => \RomegaDigital\Multitenancy\Middleware\TenantMiddleware::class,`
`'tenant.guest' => \RomegaDigital\Multitenancy\Middleware\GuestTenantMiddleware::class,`

**Comment by ltroya-as** [comment]
Hey @madurapa, 

Can you explain a little more about how this works? I reviewed the code, but it's not clear to me how the sessions are separated between tenants.

Thanks in advance!

**Comment by bilogic** [comment]
Actually, we should separate multitenancy into the following parts

1. Authentication - do you want a user to keep re-logging into every subdomain or custom domain? Probably not
2. Authorization - needs to be able recognize a tenant via domain, subfolder etc and allow/block operations, this requires a comprehensive ACL

I saw too often, instead of dealing with authorization properly, lots of methods out there promote separating the database/session etc by the time you realize you need actually authorization, too much time has been wasted on the wrong stuff.
